/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/editor.vue')['default']
    Mdeditor: typeof import('./src/components/mdeditor.vue')['default']
    MdEditor: typeof import('./src/components/md-editor.vue')['default']
    Render: typeof import('./src/components/render.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
